all:
  hosts:
    localhost:
    node1:
    node2:
    node3:
    node4:
  
  children:

    k3s:
      children:
        k3s_masters:
        k3s_workers:
        rancher:
      vars:
        ansible_user: ubuntu
        # proxy: none 
        # no_proxy: "localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"


    k3s_masters:
      hosts:
        node1:     
      vars:

    k3s_workers:
      hosts:
        node2:
        node3:
        node4:
      vars:

    rancher:
      hosts:
        node2:
      vars:
