---
# tasks file for rancher

# docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher

- name: start rancher in docker
  docker_container:
    name: myrancher
    image: rancher/rancher
    ports:
    - "80:80"
    - "443:443"
    restart_policy: unless-stopped
  become: yes
  